<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>yafphp - [ Yaf PHP Framework ]</title>
<meta name="keywords" content="yafphp,Yaf PHP Framework" />
<meta name="description" content="yafphp - [ Yaf PHP Framework ]" />
</head>
<body>
<h1><?php echo $yafphp; ?></h1>
<p>It is Yaf(Yet Another Framework) for PHP version</p>
</body>
</html>